# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a524421d38490b0709c4e259e685e7c4a1650f6df57dc65476baf6e4826b1da737cd5336fa7d3953ceb8e6ec180c22946d273b049d9ff5ffba63b1be690a711

test:
  secret_key_base: 01dd0d7eda1a9b331cceacec7cb626789fccda75e6b1398684f527b2055919cb0c74cfbfede8a08ac4a450b104b34ef1eab0f3ece62367cdc8044e772d9b15e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
